---
- name: Update Packages
  yum: name='*' state=latest

- name: Install Base Packaes
  yum: name="@Base" state=present

- name: Install Development tools Packaes
  yum: name="@Development tools" state=present

- name: Get Kernel version info
  shell: "uname -r"
  changed_when: false
  register: uname_r

- name: Vagrant VBox Dep
  yum:
    name: '{{item}}'
    state: present
  with_items:
    - kernel-devel-{{uname_r.stdout}}
    - gcc
    - binutils
    - make
    - perl
    - bzip2

- name: SSH Key Config
  authorized_key:
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
    user: vagrant
    state: present