---
# RedHat CentOS
- name: Nginx RHEL family.
  when: "ansible_os_family == 'RedHat'"
  include: rhel/add-nginx-repo.yml

- name: Nginx RHEL family.
  when: "ansible_os_family == 'RedHat'"
  include: rhel/install.yml

- name: Setup firewalld
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 7
  include: rhel/firewalld.yml

- name: Setup iptables
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= 6
  include: rhel/iptables.yml