---
- name: Install PHP-FPM 71
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi,remi-php71"
  with_items:
      - php-fpm
      - php-cli
      - php-intl
      - php-mbstring
      - php-pdo
      - php-gd
      - php-mcrypt
      - php-pear
      - php-xml
      - php-xmlrpc
      - php-mysqlnd
      - php-soap
      - php-devel

- name: Setting PHP
  lineinfile:
    dest: /etc/php.ini
    regexp: ';date.timezone ='
    line: 'date.timezone = Asia/Tokyo'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^user = apache'
    line: 'user = {{nginx_user}}'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^group = apache'
    line: 'group = {{nginx_user}}'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^listen = 127.0.0.1:9000'
    line: 'listen = {{phpfpm_socket}}'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    regexp: ';listen.owner = nobody'
    line: 'listen.owner = {{nginx_user}}'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    regexp: ';listen.group = nobody'
    line: 'listen.group = {{nginx_user}}'

- name: Setting PHP
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    regexp: ';listen.mode = 0660'
    line: 'listen.mode = 0660'

- name: set acl
  acl:
    path: /var/lib/php
    entity: "{{nginx_user}}"
    etype: user
    permissions: rw
    recursive: yes
    state: present

- name: set acl
  acl:
    path: /var/lib/php
    entity: "{{nginx_user}}"
    etype: group
    permissions: rw
    recursive: yes
    state: present

- name: Enable Service
  service:
    name: php-fpm
    enabled: yes
    state: started