---
- name: Install PHP-FPM 71
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi,remi-php71"
  with_items:
      - php-fpm
      - php-cli
      - php-intl
      - php-mbstring
      - php-pdo
      - php-gd
      - php-mcrypt
      - php-pear
      - php-xml
      - php-xmlrpc
      - php-mysqlnd
      - php-soap
      - php-devel

- name: Setting PHP.ini
  replace:
    dest: /etc/php.ini
    regexp: '^;date.timezone =.*$'
    replace: 'date.timezone = Asia/Tokyo'

- name: Setting PHP-FPM.ini
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^user ='
    line: 'user = {{nginx_user}}'

- name: Setting PHP-FPM.ini
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^group ='
    line: 'group = {{nginx_user}}'

- name: Setting PHP-FPM.ini
  lineinfile: 
    dest: /etc/php-fpm.d/www.conf
    state: present
    regexp: '^listen ='
    line: 'listen = {{phpfpm_socket}}'

- name: Setting PHP-FPM.ini
  replace: 
    dest: /etc/php-fpm.d/www.conf
    regexp: '^;listen.owner =.*$'
    replace: 'listen.owner = {{nginx_user}}'

- name: Setting PHP-FPM.ini
  replace: 
    dest: /etc/php-fpm.d/www.conf
    regexp: '^;listen.group =.*$'
    replace: 'listen.group = {{nginx_user}}'

- name: Setting PHP-FPM.ini
  replace: 
    dest: /etc/php-fpm.d/www.conf
    regexp: '^;listen.mode =.*$'
    replace: 'listen.mode = 0660'